# ./docker-compose.yml
services:
  cv_db-service:
    env_file:
      - ./.secrets
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CONTAINER: ${MYSQL_CONTAINER}
    image: mysql:9.0
    container_name: ${MYSQL_CONTAINER}
    networks:
      - cv-network
    ports:
      - 3307:3306
    volumes:
      - ./sql/schemadump.sql:/docker-entrypoint-initdb.d/dump.sql
      # - mysql-data:/var/lib/mysql
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always
    command: mysqld

  cv_api-service:
    env_file:
      - ./.secrets
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      API_IMG: ${API_IMG}
      API_TAG: ${API_TAG}
      API_CONTAINER: ${API_CONTAINER}
      MYSQL_HOST: ${MYSQL_HOST}
    build:
      context: .
      dockerfile: Dockerfile.api
    image: ${API_IMG}:${API_TAG}
    container_name: ${API_CONTAINER}
    ports:
      - 8080:8080
    depends_on:
      cv_db-service:
        condition: service_healthy
    networks:
      - cv-network
    restart: always

  cv_bff-service:
    env_file:
      - ./.secrets
    environment:
      BFF_IMG: ${BFF_IMG}
      BFF_TAG: ${BFF_TAG}
      BFF_CONTAINER: ${BFF_CONTAINER}
      API_IP: ${API_IP}
      API_PORT: ${API_PORT}
    build:
      context: .
      dockerfile: Dockerfile.bff
    image: ${BFF_IMG}:${BFF_TAG}
    container_name: ${BFF_CONTAINER}
    ports:
      - "5000:5000"
    networks:
      - cv-network
    restart: always
    depends_on:
      cv_db-service:
        condition: service_healthy

networks:
  cv-network:
    name: cv-network
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.18.0.0/16
    #       gateway: 172.18.0.1
# volumes:
#   mysql-data:
#     name: cv_db-volume

  # venom:
  #   build: 
  #     context: tests
  #   container_name: venom
  #   profiles: [ "test" ]
  #   depends_on:
  #     api:
  #       condition: service_healthy
