services:
  db:
    build:
      context: ./sql
    image: db:8.0
    container_name: db
    networks:
      - my-network
    ports:
      - "3307:3306" # 
    env_file:
      - .env
    volumes:
      - ./sql/schemadump.sql:/docker-entrypoint-initdb.d/dump.sql
      #- db-data:/var/lib/mysql
      - ./sql/db.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always


  api:
    build:
      context: ./api
    image: api
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - my-network
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "60s", "./main"]


  bff:
    build:
      context: ./bff
    image: bff
    container_name: bff
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - my-network
    command: ["dockerize", "-wait", "tcp://api:8080", "-timeout", "60s", "python3", "app.py", "-i", "api", "-p", "8080"]


networks:
  my-network:
    driver: bridge


volumes:
  db-data:
