version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: go-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - my-network
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "60s", "./main"]

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    container_name: bff-service
    ports:
      - "8081:8080"
    depends_on:
      - api
    restart: always
    networks:
      - my-network
    env_file:
      - .env
    command: ["dockerize", "-wait", "tcp://api:8080", "-timeout", "60s", "python3", "app.py"]

  db:
    image: mysql:5.7
    env_file:
      - .env
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - ./sql/schemadump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
