services:
  cv_db-service:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CONTAINER: ${MYSQL_CONTAINER}
    container_name: ${MYSQL_CONTAINER}
    networks:
      - cv-network
    ports:
      - 3307:3306
    volumes:
      - ./sql/schemadump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      interval: 12s
      timeout: 8s
      retries: 5
      start_period: 5s
    restart: always
    command: >
      mysqld; sh -c "
      echo 'Europe/London' > /etc/timezone && \
      cp /usr/share/zoneinfo/Europe/London /etc/localtime"

  cv_api-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      API_IMG: ${API_IMG}
      API_TAG: ${API_TAG}
      API_CONTAINER: ${API_CONTAINER}
      MYSQL_HOST: ${MYSQL_HOST}
    image: ${API_IMG}:${API_TAG}
    container_name: ${API_CONTAINER}
    ports:
      - 8080:8080
    depends_on:
      cv_db-service:
        condition: service_healthy
    networks:
      - cv-network
    restart: always

  cv_bff-service:
    environment:
      BFF_IMG: ${BFF_IMG}
      BFF_TAG: ${BFF_TAG}
      BFF_CONTAINER: ${BFF_CONTAINER}
      API_IP: ${API_IP}
      API_PORT: ${API_PORT}
    build:
      context: .
      dockerfile: Dockerfile.bff
    image: ${BFF_IMG}:${BFF_TAG}
    container_name: ${BFF_CONTAINER}
    ports:
      - "5000:5000"
    networks:
      - cv-network
    restart: always
    depends_on:
      cv_db-service:
        condition: service_healthy

networks:
  cv-network:
    name: cv-network
    driver: bridge
