version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: api_container
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    networks:
      - my-network
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "60s", "./main"]

  bff:
    build:
      context: ./bff
    container_name: bff_container
    ports:
      - "5000:8080"
    restart: always
    networks:
      - my-network
    env_file:
      - .env
    command: ["dockerize", "-wait", "tcp://127.0.0.1:8080", "-timeout", "60s", "python3", "app.py", "-i", "127.0.0.1", "-p", "8080"]

  db:
    image: mysql:5.7
    env_file:
      - .env
    container_name: db_container
    ports:
      - "3306:3306"
    volumes:
      - ./sql/schemadump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
