# curl -s https://registry.hub.docker.com/v2/repositories/library/python/tags | jq -r '.results[] | .name + " - " + (.last_updated | split("T")[0])'
FROM python:3.11-slim

WORKDIR /bff/

COPY bff/ .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "./app/app.py"]
