#? CV_project/.github/workflows/integration-tests.yml
---
name: integration tests

# events workflow
on:
  push:
    paths:
      - api/tests/**
      - .github/workflows/integration-tests.yml
    branches:
      - main
  pull_request:
    paths:
      - api/tests/**
      - .github/workflows/integration-tests.yml
    branches:
      - main
  workflow_dispatch: null

# jobs workflow
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0
      - name: install dependencies
        run: go mod tidy
        working-directory: ./api/tests
      - name: run integration tests
        run: go test -v ./tests/...
        working-directory: ./api/tests
      - name: verify go installation
        run: go version
      - name: cache go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('api/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
